/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsrRouteImport } from './routes/ssr'
import { Route as OutletRouteImport } from './routes/outlet'
import { Route as CsrRouteImport } from './routes/csr'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaticRouteIndexRouteImport } from './routes/staticRoute/index'
import { Route as StaticRouteChildRouteImport } from './routes/staticRoute/child'
import { Route as RestSplatRouteImport } from './routes/rest/$'
import { Route as OutletChildRouteImport } from './routes/outlet/child'
import { Route as DynamicIdRouteImport } from './routes/dynamic/$id'

const SsrRoute = SsrRouteImport.update({
  id: '/ssr',
  path: '/ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletRoute = OutletRouteImport.update({
  id: '/outlet',
  path: '/outlet',
  getParentRoute: () => rootRouteImport,
} as any)
const CsrRoute = CsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticRouteIndexRoute = StaticRouteIndexRouteImport.update({
  id: '/staticRoute/',
  path: '/staticRoute/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticRouteChildRoute = StaticRouteChildRouteImport.update({
  id: '/staticRoute/child',
  path: '/staticRoute/child',
  getParentRoute: () => rootRouteImport,
} as any)
const RestSplatRoute = RestSplatRouteImport.update({
  id: '/rest/$',
  path: '/rest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletChildRoute = OutletChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => OutletRoute,
} as any)
const DynamicIdRoute = DynamicIdRouteImport.update({
  id: '/dynamic/$id',
  path: '/dynamic/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/csr': typeof CsrRoute
  '/outlet': typeof OutletRouteWithChildren
  '/ssr': typeof SsrRoute
  '/dynamic/$id': typeof DynamicIdRoute
  '/outlet/child': typeof OutletChildRoute
  '/rest/$': typeof RestSplatRoute
  '/staticRoute/child': typeof StaticRouteChildRoute
  '/staticRoute/': typeof StaticRouteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/csr': typeof CsrRoute
  '/outlet': typeof OutletRouteWithChildren
  '/ssr': typeof SsrRoute
  '/dynamic/$id': typeof DynamicIdRoute
  '/outlet/child': typeof OutletChildRoute
  '/rest/$': typeof RestSplatRoute
  '/staticRoute/child': typeof StaticRouteChildRoute
  '/staticRoute': typeof StaticRouteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/csr': typeof CsrRoute
  '/outlet': typeof OutletRouteWithChildren
  '/ssr': typeof SsrRoute
  '/dynamic/$id': typeof DynamicIdRoute
  '/outlet/child': typeof OutletChildRoute
  '/rest/$': typeof RestSplatRoute
  '/staticRoute/child': typeof StaticRouteChildRoute
  '/staticRoute/': typeof StaticRouteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/csr'
    | '/outlet'
    | '/ssr'
    | '/dynamic/$id'
    | '/outlet/child'
    | '/rest/$'
    | '/staticRoute/child'
    | '/staticRoute/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/csr'
    | '/outlet'
    | '/ssr'
    | '/dynamic/$id'
    | '/outlet/child'
    | '/rest/$'
    | '/staticRoute/child'
    | '/staticRoute'
  id:
    | '__root__'
    | '/'
    | '/csr'
    | '/outlet'
    | '/ssr'
    | '/dynamic/$id'
    | '/outlet/child'
    | '/rest/$'
    | '/staticRoute/child'
    | '/staticRoute/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CsrRoute: typeof CsrRoute
  OutletRoute: typeof OutletRouteWithChildren
  SsrRoute: typeof SsrRoute
  DynamicIdRoute: typeof DynamicIdRoute
  RestSplatRoute: typeof RestSplatRoute
  StaticRouteChildRoute: typeof StaticRouteChildRoute
  StaticRouteIndexRoute: typeof StaticRouteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ssr': {
      id: '/ssr'
      path: '/ssr'
      fullPath: '/ssr'
      preLoaderRoute: typeof SsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet': {
      id: '/outlet'
      path: '/outlet'
      fullPath: '/outlet'
      preLoaderRoute: typeof OutletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csr': {
      id: '/csr'
      path: '/csr'
      fullPath: '/csr'
      preLoaderRoute: typeof CsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staticRoute/': {
      id: '/staticRoute/'
      path: '/staticRoute'
      fullPath: '/staticRoute/'
      preLoaderRoute: typeof StaticRouteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staticRoute/child': {
      id: '/staticRoute/child'
      path: '/staticRoute/child'
      fullPath: '/staticRoute/child'
      preLoaderRoute: typeof StaticRouteChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rest/$': {
      id: '/rest/$'
      path: '/rest/$'
      fullPath: '/rest/$'
      preLoaderRoute: typeof RestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet/child': {
      id: '/outlet/child'
      path: '/child'
      fullPath: '/outlet/child'
      preLoaderRoute: typeof OutletChildRouteImport
      parentRoute: typeof OutletRoute
    }
    '/dynamic/$id': {
      id: '/dynamic/$id'
      path: '/dynamic/$id'
      fullPath: '/dynamic/$id'
      preLoaderRoute: typeof DynamicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OutletRouteChildren {
  OutletChildRoute: typeof OutletChildRoute
}

const OutletRouteChildren: OutletRouteChildren = {
  OutletChildRoute: OutletChildRoute,
}

const OutletRouteWithChildren =
  OutletRoute._addFileChildren(OutletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CsrRoute: CsrRoute,
  OutletRoute: OutletRouteWithChildren,
  SsrRoute: SsrRoute,
  DynamicIdRoute: DynamicIdRoute,
  RestSplatRoute: RestSplatRoute,
  StaticRouteChildRoute: StaticRouteChildRoute,
  StaticRouteIndexRoute: StaticRouteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
